[project]
name = "ctrlc-openai-o3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.109.0",
    "uvicorn>=0.27.0",
    "python-multipart>=0.0.6",
    "pyperclip>=1.8.2",
    "jinja2>=3.1.2",
]
